### PR TITLE
Signals to allow a plugin to be developped

### PR DESCRIPTION
**Pull request by ThomSawyer**
I would like to develop a plugin that would allow saving authenticated users' cookie preferences in the database. 

In order to make the plugin work, I would need the three following changes:
* `CleanCookiesMiddleware` needs to be fixed.
* Adding `accept_cookie` and `decline_cookie` signals.
* Releasing a new pypi version

Those changes would allow me to avoid a fork for my new plugin. [See plugin here](https://github.com/briefmnews/django-cookie-consent-authenticateduser)(still under development).

I'm ready to be part of the main app maintainers if needed.

### CODE REVIEW

**Comment by 9mido** [comment]
@ThomSawyer Thanks for this. We need more maintainers for this project. If you could fix some of my bugs I would love you forever :) 

@bmihelac the maintainer has been MIA and nobody knows where he is. 

Just wondering would this allow for new database entries when COOKIE_CONSENT_LOG_ENABLED = True? Not everyone including me would need this type of feature. Users could keep deleting cookies then allow them over and over again and fill up the database quickly. So my recommendation would be to make a setting to turn this on/off if you don't already have it. I would make it separate from COOKIE_CONSENT_LOG_ENABLED if it has different functionality.

**Comment by ThomSawyer** [comment]
@9mido The `COOKIE_CONSENT_LOG_ENABLED` already handles the situation you are discribing.
If set to `False` there will be no log entries in the database. You can see it in the codebase:
* https://github.com/bmihelac/django-cookie-consent/blob/master/cookie_consent/util.py#L95
* https://github.com/bmihelac/django-cookie-consent/blob/master/cookie_consent/util.py#L117

I think that your problem might be that the [latest release on PyPI](https://pypi.org/project/django-cookie-consent/#description) (0.2.6) doesn't allow you to enable / disable this setting.

To fix your problem quickly, you can install the package from Github's master branch instead of PyPI:
```
pip install -e git://github.com/bmihelac/django-cookie-consent@master#egg=django-cookie-consent
```

**Comment by 9mido** [comment]
@ThomSawyer Thanks I was already aware of PyPi not being updated and needing to use the command to use the latest version as you have kindly added here. I have been using the COOKIE_CONSENT_LOG_ENABLED successfully for some time now. 

I am confused. Why create a completely separate dedicated app if you could have another additional setting merged to the main django-cookie-consent library to let people decide if they want to use it or not? What I was trying to suggest was just make a setting for your plugin something like COOKIE_CONSENT_PLUGIN_SIGNALS = True|False or whatever you want to call it so that everyone could use/not use it from just 1 app instead of 2? If you made a setting like that, then users like me wouldn't be forced to have anything logged to the database for users regarding their cookie acceptances/declines. And users like you could decide to have it logged in the database if they wish. 

Or do you mean in the meantime before PyPi is updated with the main django-cookie-consent to have a separate app so that people could have an updated one from you for the time being until the main one gets updated?

**Comment by some1ataplace** [comment]
@ThomSawyer Wondering why you closed this?

**Comment by ThomSawyer** [comment]
I've been working on a fork to solve my use case.

It seems that the code I wrote couldn't be merged anymore. I'm willing to reopen this issue if the maintainers agree.

**Comment by some1ataplace** [comment]
@ThomSawyer It wouldn't hurt to reopen it or make a new one.

**Pull request closed without merging**
